
spring:
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USERNAME}        
        password: ${PROD_DB_PASSWORD}
    sql:
        init:
            mode: always
cloud:
    aws:
        accessKey: ${AWS_S3_KEY}
        secretKey: ${AWS_S3_SECRET}
        region:
            static: ${AWS_S3_REGION}
        stack:
            auto: false
application:
    bucket:
        name: ${AWS_S3_NAME}